[project]
name = "bessel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jax>=0.9.0.1",
    "pytest>=9.0.2",
    "python-flint>=0.8.0",
]
